### ISSUE TITLE
Backend 진행상황

### ISSUE THREAD

**Issue by JustKode** [Dcom-KHU/Sigmund_finance#2]
# 완료
- DB 모델 구현 완료
- api 함수 구현 완료
- url 구현 완료

# 미완료
- 서버에 아직 올리지 않음
- 도큐먼트 작성 아직 못함
- 토큰 구현 곧 할 예정

**Comment by JustKode** [comment]
오늘 시험이어서 너무 힘들었습니다 ㅠㅠ

**Comment by kairos03** [comment]
코드 올리고 진행사항 [Metting log](https://github.com/Dcom-KHU/Sigmund_finance/wiki/Meeting-Log-2018.10.10) 여기에 정리해서 올려주세요

**Comment by kairos03** [comment]
위키의 미팅로그에 정리해서 올려주세요 @JustKode
