### ISSUE TITLE
DB model 설계

### ISSUE THREAD

**Issue by graykode** [Dcom-KHU/Sigmund_finance#4]
## PROBLEM

위키 읽고 몇가지 문제점 적어봅니다.

확정이되면 자료형이랑 default 설정에 대해서도 위키에 올려볼께여

## Member Table

1. 로그인 기능이 있는데 아이디, 비밀번호를 입력하는 칼럼의 존재 여부? 

   이전에 php laravel에서 설계해서 사용한 모델이예여
![](https://image.ibb.co/e8VSGV/image.png)

  추가해야할 칼럼

- **유니크한 키** : 단조 증가하면서 유니크한 데이터 한 row을 나타낼수 있는 컬럼
- Student_Id(학번) : **입학연도? 아님 단순 입학연도를 말하는 건지??**
- **아이디를 나타내는 컬럼**
- **비밀번호를 나타내는 컬럼**
- Name(이름 실명)
- Grade(1,2,3,4)
- Status(재학,휴학,군휴학,졸업,휴면)
- Email
- Phone
- **가장 최근에 접속한 시간을 담는 컬럼** 
- Position
- **이번 학기에 회비를 냈는지 체크하는 컬럼**

2. 휴면 상태라는 기능이 필요한지?

   제가 갖고 있는 DB로보면 군휴학 등으로 인해 또한 전역일 후에 사이트에 들어오지 않는 사용자가 꽤 많아여! 휴면 상태일 경우 단순한 행삭제가 아닌 소프트한 삭제였으면 좋겠습니다!

## Finance Info Table

- **유니크한 키** : 단조 증가하면서 유니크한 데이터 한 row을 나타낼수 있는 컬럼

  > 만약에 사용일과 사용처 등등이 우연히 같으면 구분할 법이 없기 때문

- Date

- Usage

- Detail

- User

- Income

- Outcome

- Total

## Collect Table

  **매 학기 동아리 회비는 무조건 내게 되있으므로 매 학기초에 collect table에다 meber에서 학교 재학생인 데이터를 가져와 모두 넣고 ** 회비를 낸 사람만 collect table에서 삭제해 주어, **동아리 회비**는 총무가 안낸 사람을 입력해주는 방식이 아닌 자동으로 백엔드에서 계산되는 방식으로 구현하는게 더 편할 것 같습니다.

- **유니크한 키** : 단조 증가하면서 유니크한 데이터 한 row을 나타낼수 있는 컬럼

- Date (사용일)
- Usage (사용처)
- Detail (상세)
- User (사용자)
- Amount (걷을 돈) 

개인이 로그인시 collect table에서 자신의 이름으로 된 데이터만 가져와서 알람 기능을 해주면 자신이 어떤 돈을 안냈는지 알 것 같습니다.

**Comment by kairos03** [comment]
![2018db](https://user-images.githubusercontent.com/6357456/48348008-568ea400-e6c3-11e8-9427-f7b8ab0d69e9.jpg)

다음과 같이 db설계하였습니다.

user, finance table은 기존과 같고, collect table을 finance와 합쳤습니다. 겹치는 부분이 많아서 단순히 finance table에서 is_collect 컬럼을 추가해서 냈는지 안냈는지 체크하면 될 것 같습니다.
